### ISSUE TITLE
Feature request: 動画切り替わり時、エッジ付近のギザ取りを自動化

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/annotateFromVideo#12]
**概要**
- 動画が切り替わる際にオブジェクトのエッジ付近の領域を手作業で調整している
- 多少適当に領域指定しても後処理できれいに調整される
- →動画切り替え後最初の一枚の「エッジ付近の少し外側を黒塗りする」作業を自動化

**目的**
- 人間の作業を楽にするため

**提案内容**
- [ ] 動画切り替わり後の最初の一枚のみ、エッジ外側への黒線をnewmask2に追加する処理を入れる
- [ ] エッジの検出は黒以外の色を背景にした場合も対応できるようにする（単色前提）
- [ ] 上記の機能の有効・無効を切り替えられるようにする

![Screenshot from 2022-05-18 12-48-13](https://user-images.githubusercontent.com/19720932/168953273-ea381570-ae22-4781-9191-6ebc5e4d49f4.png)

**Comment by AiriYokochi** [comment]
スキップしてもう一度やればできると思います

**Comment by nyxrobotics** [comment]
下記へ移行
https://github.com/sbgisen/video2coco/issues/15
