### ISSUE TITLE
輪郭追跡の処理が終わらない

### ISSUE THREAD

**Issue by YS-KID** [sbgisen/annotateFromVideo#7]
**概要**
65行目から124行目までの輪郭追跡の処理が無限ループに入ることがある．

**再現手順**
以下の映像をアノテーションしている途中に発生した．
/robotics-nas/members/yokochi/2022_robocup_at_home/video/strawberry/vokoscreenNG-2022-05-12_18-33-06.mkv
/robotics-nas/members/yokochi/2022_robocup_at_home/video/strawberry/vokoscreenNG-2022-05-12_18-35-06.mkv

**修正しないとどう困るか**

**原因**
88行目から124行目のwhile文でbreakできていないため、発生している無限ループのようである．

**修正案**

**Comment by AiriYokochi** [comment]
メモ

```
^[^CTraceback (most recent call last):
  File "annotateFromVideo/annotateFromVideo.py", line 481, in <module>
    img_contour, importantCorners = trackContour(img_bin)
  File "annotateFromVideo/annotateFromVideo.py", line 111, in trackContour
    if (img_bin[y + b][x + a] == 255):
```

**Comment by YS-KID** [comment]
mustard_vokoscreenNG-2022-05-12_18-22-14_12.mkv でも発生した

**Comment by AiriYokochi** [comment]
フリーズする画像ファイルありますか？

**Comment by YS-KID** [comment]
スクショし忘れました💦
明日スクショして貼ります！！

**Comment by nyxrobotics** [comment]
フリーズ直前
![Screenshot from 2022-05-17 21-29-14](https://user-images.githubusercontent.com/19720932/168811138-0952f255-4bbd-46e0-89e3-55c6669b8071.png)

フリーズ直後
![Screenshot from 2022-05-17 21-29-34](https://user-images.githubusercontent.com/19720932/168811171-65d853b3-d852-41cf-b3b6-6eaab43e2675.png)

多分coutourが閉じられなくなっているんですがまだ原因わからず

**Comment by nyxrobotics** [comment]
仕組みは不明だが、元々のようにtrackContourに与える画像にdilate(1ピクセルふくらませる処理)をかけると全部通るようになる。

```python
        # 輪郭追跡とコーナーの単純化
        contour_img = cv2.dilate(img_bin, kernel, iterations=1)
        img_contour, importantCorners = trackContour(contour_img)
```

**Comment by nyxrobotics** [comment]
失礼もともとは3縮めた後4膨らましてました
https://github.com/taketake25/annotateFromVideo/blob/a481b62a6ba08093ba2c6806d48d9c5191fddeb9/annotateFromVideo.py#L340-L350

**Comment by nyxrobotics** [comment]
- cv2.dilate(img_bin, kernel, iterations=1)でとりあえずエラーはなくなる
- cv2.dilate(img_bin, kernel, iterations=4)すると黒いエッジが見える

という状況なので、一旦iterations=1する方針にしようと思います。
